### ISSUE TITLE
"Module remote_tmp /etc/step-ca/.ansible/tmp did not exist [...]"

### ISSUE THREAD

**Issue by strarsis** [maxhoesel/ansible-collection-smallstep#102]
When applying the `step_ca` role of this collection for the first time:
````
TASK [maxhoesel.smallstep.step_ca : Initialize CA] *****************************
[WARNING]: Module remote_tmp /etc/step-ca/.ansible/tmp did not exist and was
created with a mode of 0700, this may cause issues when running as another
user. To avoid this, create the remote_tmp dir with the correct permissions
manually
````
I saw this warning also for other ansible playbooks and roles. Is this something that has to be ensured globally, or should/can this `step_ca` role/this collection itself ensure that the directory is first created with proper permissions?

**Comment by maxhoesel** [comment]
Hm, how are you connecting to your CA server? I don't get that message in my CI runs, so I'm not sure where the message is coming from.

If you are connecting to your CA host as an unprivileged user and then use become to run this playbook, the warning might be related to [that(https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user), but I'm honestly not sure.

**Comment by strarsis** [comment]
@maxhoesel: I install it on a Vagrant box (CentOS 7.x) with default vagrant user and `become: true`.
As `become` is used and that `vagrant` user is used to become root, this seems to be indeed related to the warning in the docs.

**Comment by maxhoesel** [comment]
Yea, it's probably related to that then. By the way, CentOS 7 is not officially supported by this collection, so you might run into more issues down the road. You can check the supported Distributions in the role READMEs

**Comment by strarsis** [comment]
@maxhoesel: CentOS support would be great! Because especially CentOS needs manual steps in contrast to other distributions where packages are available.
