### ISSUE TITLE
root and intermediate password files not created

### ISSUE THREAD

**Issue by strarsis** [maxhoesel/ansible-collection-smallstep#122]
`step-ca` service doesn't start because the root and intermediate password files are missing.
Manually creating these files make the `step-ca` service start.
The role should ensure these files are present - but the files are not present and the role is skipped:
````
TASK [maxhoesel.smallstep.step_ca : Create root and intermediate password files] ***
skipping: [localca] => (item=None)
skipping: [localca] => (item=None)
skipping: [localca]
````

https://github.com/maxhoesel/ansible-collection-smallstep/blob/8c9143efd1aa22c63d693d4d92d475147cdbf5be/roles/step_ca/tasks/init.yml#L30-L42

**Comment by maxhoesel** [comment]
The only way I can see that happening is if you already had a CA initialized (or at least had a ca.json present, [that's how the role checks for an existing CA](https://github.com/maxhoesel/ansible-collection-smallstep/blob/6634db70986d0bd6cf6a9222b470f4c23ed816b4/roles/step_ca/tasks/init.yml#L2)). In that case the role skips the entire initialization taskset, which includes the password file creation.

That seems like a pretty rare situation to me. That said, I think it's reasonable to always create the intermediate password file, as it's required for CA operation. The root password file is only needed during initialization on the other hand.

**Comment by strarsis** [comment]
Correct, the role runs multiple times and the initialized CA folder is mounted into the system/VM from the outside (development/staging VM), so one can add the certs as trusted once and use them between VM resets/snapshots, etc.

@maxhoesel: Yes! Always ensuring that these password files are in place (more granularity) would be a good idea!

**Comment by maxhoesel** [comment]
Ah, okay! This should be fixed in https://github.com/maxhoesel/ansible-collection-smallstep/pull/123.
