### ISSUE TITLE
tagged version v. "release" changelog and version update skew

### ISSUE THREAD

**Issue by eengstrom** [maxhoesel/ansible-collection-smallstep#69]
Max,

It seems a bit odd to me the process you are following to make a git tag for a version (e.g. `v0.4.5`) and **then** add a commit updating the `CHANGELOG` and version number in the `galaxy.yml`.   

I noted this as we are using your github.com repository and tags rather than Galaxy in our `requirements.yml`, and therefore when we are getting the tagged version, the `galaxy.yml` and changelog are never "up to date".  

Would it not be better to update the version in `galaxy.yml` and the `CHANGELOG` and tag that commit?

**Comment by eengstrom** [comment]
By example, `requirements.yml` fragment:

```yaml
collections:
  - name: https://github.com/maxhoesel/ansible-collection-smallstep.git
    type: git
    version: v0.4.5
```

... and installation output via `ansible-galaxy`:

```bash
$ ansible-galaxy collection install -p collections -r requirements.yml --ignore-errors --force
Installing 'maxhoesel.smallstep:0.4.4' to '.../ansible/collections/ansible_collections/maxhoesel/smallstep'
Created collection for maxhoesel.smallstep at .../ansible/collections/ansible_collections/maxhoesel/smallstep
maxhoesel.smallstep (0.4.4) was installed successfully
```

Note the feedback says `version 0.4.4`, which of course is coming from `galaxy.yml`.

**Comment by maxhoesel** [comment]
Just had a look at the release workflow, it seems like the create-action doesn't recognize the locally created release commit and thus uses the previous commit for the release tag. This is not intentional - the release tag should point to the, well, release.

https://github.com/maxhoesel/ansible-collection-smallstep/pull/70 should fix this.

**Comment by eengstrom** [comment]
Thanks for fixing - I didn't think to look for a github workflow.
